### PR TITLE
Allow readonly between phpdoc and property name

### LINKED ISSUE #446: Throws Missing PHP DocBlock for class property warning if readonly used in class property | PHP 8.1
### Preconditions

1. Magento 2.4.6 EE/CE
2. Magento Coding Standard v31 i.e `magento/magento-coding-standard: 31`
3. PHP 8.1|8.2

### Steps to reproduce

1.  Create a class
```
<?php
declare(strict_types=1);

namespace Vendor\Module\Handler;

use Vendor\Module\Service\IsLoggingServiceInterface;
use Magento\Framework\Filesystem\DriverInterface;
use Magento\Framework\Logger\Handler\Base as BaseHandler;
use Monolog\Logger;


class IfConfigured extends BaseHandler
{
    /**
     * @var IsLoggingServiceInterface
     */
    private readonly IsLoggingServiceInterface $loggingEnabledService;
    
}
```

4. `vendor/bin/phpcs --standard=Magento2 . -s`
5.

### Expected result

1. It should not throw a warning
2.

### Actual result

1. Throws warning 
```
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------
 17 | WARNING | Missing PHP DocBlock for class property.
    |         | (Magento2.Commenting.ClassPropertyPHPDocFormatting.Missing)

```
3.

### PR DESCRIPTION
**Pull request by sandipklevu**
**Description**: While making variable `readonly` was throwing a warning

Fixes https://github.com/magento/magento-coding-standard/issues/446

### CODE REVIEW

**Review by fredden — APPROVED** [review]

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sandipklevu,
Could you please add a test coverage for your change?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sandipklevu** [comment]
@magento  import pr to magento-commerce/magento-coding-standard repository

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sidolov the Pull Request is successfully imported.

**Pull request merged**
