### PR TITLE
upgrade php codesniffer up to version 3.4

### PR DESCRIPTION
**Pull request by sergeynezbritskiy**

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=85) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=85) before we can accept your contribution.<br/>

**Comment by lenaorobei** [comment]
Hi @sergeynezbritskiy! Could you please sign [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=85) so I'll be able to process your PR.

**Comment by lenaorobei** [comment]
@sergeynezbritskiy could you please sign [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=85) so I'll be able to include your improvement in the next major release.

**Comment by sergeynezbritskiy** [comment]
> @sergeynezbritskiy could you please sign [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=85) so I'll be able to include your improvement in the next major release.
@lenaorobei done, thanks

**Pull request merged**
