### PR TITLE
Automatically remove useless comments

### PR DESCRIPTION
**Pull request by fredden**
When issues are detected and classified as `Magento2.Commenting.ClassAndInterfacePHPDocFormatting.ForbiddenTags` or `Magento2.Commenting.ClassAndInterfacePHPDocFormatting.InvalidDescription`, these can be fixed by removing the offending comment.

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sinhaparul** [comment]
@magento import PR to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sinhaparul the Pull Request is successfully imported.

**Comment by sidolov** [comment]
@magento import PR to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sidolov the Pull Request is successfully imported.

**Comment by orlangur** [comment]
> Magento2.Commenting.ClassAndInterfacePHPDocFormatting.InvalidDescription

Well, the whole point of this sniff was to enforce meaningful descriptions :)
Invalid description removal goes against this.

**Comment by ihor-sviziev** [comment]
@orlangur, from the message:
> description must contain meaningful information beyond what its name provides **or be removed.**

So it does make sense to auto-remove it
In general, enforcing adding a description for self-descriptive method/class is a bad idea

**Pull request merged**
