### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by snoop0x7b**
I found a small typo in README.md. Figured I'd fix it and send over a pull request for it.

### CODE REVIEW

**Review by fredden — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sidolov** [comment]
@snoop0x7b  could you please sign Adobe CLA? Thanks!

**Comment by snoop0x7b** [comment]
> @snoop0x7b could you please sign Adobe CLA? Thanks!

Signed! Thanks

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sidolov the Pull Request is successfully imported.

**Pull request merged**
