### PR TITLE
Add Sniff for check autovivification on array

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

Added sniff for check autovivification on array.

Addresses backward incompatible change in PHP 8.1: https://wiki.php.net/rfc/autovivification_false

### Fixed Issues (if relevant)

1. magento/magento2#34509

### Contribution checklist (*)
 - [ ] Author has signed the [Adobe CLA](https://opensource.adobe.com/cla.html)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]

**Comment by sivaschenko** [comment]
Thank you for the valuable contribution @anzin ! Can you please add the unit test for this sniff. Having the test code will make it much easier to review the PR.

**Review by loginesta — DISMISSED** [review]

**Review by andrewbess — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@sivaschenko an error occurred during the Pull Request import.

**Review by loginesta — APPROVED** [review]

**Comment by svera** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@svera an error occurred during the Pull Request import.

**Pull request merged**
