### PR TITLE
Fix TypeError for phpcs->addWarning()

### PR DESCRIPTION
**Pull request by fredden**
Argument 4 of PHP_CodeSniffer->addWarning() must be an array; integer given.

https://github.com/squizlabs/PHP_CodeSniffer/blob/a71aad2074891a5fc4b2f7e891282c9333830efd/src/Files/File.php#L683

        Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, int given in /srv/www/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
        Stack trace:
        #0 /srv/www/vendor/squizlabs/php_codesniffer/src/Files/File.php(1056): vsprintf('Direct throw of...', 531)
        #1 /srv/www/vendor/squizlabs/php_codesniffer/src/Files/File.php(706): PHP_CodeSniffer\Files\File->addMessage(false, 'Direct throw of...', 67, 4, 'FoundDirectThro...', 531, 8, false)
        #2 /srv/www/vendor/magento/magento-coding-standard/Magento2/Sniffs/Exceptions/DirectThrowSniff.php(48): PHP_CodeSniffer\Files\File->addWarning('Direct throw of...', 526, 'FoundDirectThro...', 531)
        #3 /srv/www/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): Magento2\Sniffs\Exceptions\DirectThrowSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 526)
        #4 /srv/www/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
        #5 /srv/www/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
        #6 /srv/www/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
        #7 /srv/www/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
        #8 /srv/www/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
        #9 {main}
          thrown in /srv/www/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1056

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@sivaschenko please review

**Comment by ihor-sviziev** [comment]
Hi @fredden,
Could you provide some steps to reproduce?

**Comment by fredden** [comment]
Easiest way to reproduce is to run `php -r 'var_dump(vsprintf("%d", [1]));'` and `php -r 'var_dump(vsprintf("%d", 1));'` with PHP v8.0. With PHP v8.0, running `vendor/bin/phpunit` shows the error.

Screenshot_2021-07-27_00-41-59

**Review by ihor-sviziev — APPROVED** [review]
Hi,

I tested these changes on top of PHP 8 - works fine.
Before these changes:
image
https://github.com/magento/magento-coding-standard/runs/3170690636

After:
image

https://github.com/magento/magento-coding-standard/runs/3170628234

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by magento-engcom-team** [comment]
@sivaschenko the pull request successfully imported.

**Pull request merged**
