### PR TITLE
Fixed undefined variable error in AutogeneratedClassNotInConstructorSniff

### PR DESCRIPTION
**Pull request by sivaschenko**
Fixes: https://github.com/magento/magento-coding-standard/issues/314

Refactored the sniff for better readability, simplified and fixed the implementation.
Added additional filtering by autogenerated class suffixes (Proxy and Interceptors are not covered as they are handled by DiscouragedDependenciesSniff)

Test results on magento2 codebase:

```

$ vendor/bin/phpcs --standard=Magento2 --sniffs=Magento2.PHP.AutogeneratedClassNotInConstructor magento2/app/code

FILE: magento2/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
67 | ERROR | Class \Magento\Framework\Controller\Result\JsonFactory needs to be requested in constructor, otherwise compiler will not be able to
|       | find and generate this classes
------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: magento2/app/code/Magento/CatalogSearch/Model/ResourceModel/Advanced/Collection.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
194 | ERROR | Class \Magento\Framework\Api\Search\SearchResultFactory needs to be requested in constructor, otherwise compiler will not be able to
|       | find and generate this classes
------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: magento2/app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
181 | ERROR | Class \Magento\Framework\Api\Search\SearchResultFactory needs to be requested in constructor, otherwise compiler will not be able to
|       | find and generate this classes
------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: magento2/app/code/Magento/Catalog/Controller/Adminhtml/Product/Builder.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
81 | ERROR | Class \Magento\Store\Model\StoreFactory needs to be requested in constructor, otherwise compiler will not be able to find and generate
|       | this classes
------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: magento2/app/code/Magento/Rule/Model/AbstractModel.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------------------------
495 | ERROR | Class \Magento\Framework\Api\ExtensionAttributesFactory needs to be requested in constructor, otherwise compiler will not be able to
|       | find and generate this classes
507 | ERROR | Class \Magento\Framework\Api\AttributeValueFactory needs to be requested in constructor, otherwise compiler will not be able to find
|       | and generate this classes
------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: magento2/app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
208 | ERROR | Class \Magento\ConfigurableProduct\Helper\Product\Options\Factory needs to be requested in constructor, otherwise compiler will not be
|       | able to find and generate this classes
------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: magento2/app/code/Magento/Customer/Controller/Account/Logout.php
------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------
75 | ERROR | Class CookieMetadataFactory needs to be requested in constructor, otherwise compiler will not be able to find and generate this classes
------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 1 mins, 59.01 secs; Memory: 64MB

```

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@sivaschenko an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Pull request merged**
