### PR TITLE
AC-1355: Move JSCS into magento-coding-standards repo

### PR DESCRIPTION
**Pull request by loginesta**
https://jira.corp.magento.com/browse/AC-1355 Move JSCS into magento-coding-standards repo

### CODE REVIEW

**Review by jcuerdo — APPROVED** [review]

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Review by svera — APPROVED** [review]

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Pull request merged**
