### PR TITLE
#210: Fixed HtmlDirectiveSniff.php from causing the Fatal Error for c…

### PR DESCRIPTION
**Pull request by asheem-patro**
…lass not found

Fixes https://github.com/magento/magento-coding-standard/issues/210

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @asheem-patro,
Could you provide some steps to reproduce?

**Comment by asheem-patro** [comment]
Hi @ihor-sviziev 

Install the magento-coding-standards in some different directory other than the Magento root. Then run the phpcs using `/var/www/html/magento-coding-standard/vendor/bin/phpcs --standard=Magento2 app/code/`

**Comment by asheem-patro** [comment]
@ihor-sviziev - `\Magento\Framework\Filter\Template` this framework class has been used inside `\Magento2\Sniffs\Html\HtmlDirectiveSniff` to use some constants. Due to which we are getting the class not found error. It is having a problem in using the magento-coding-standard on the bitbucket pipelines.

Please let me know if you want some more clarifications.

**Comment by ihor-sviziev** [comment]
@asheem-patro,
Interesting... for some reason, it's not failing when we're running it inside the coding standard repo...
https://github.com/magento/magento-coding-standard/runs/3218975370?check_suite_focus=true
image

I think it has to fail. We should fix that at first, and later on accept your PR :)

**Comment by asheem-patro** [comment]
@ihor-sviziev - I am also wondering the same thing. It still fails for me without this fix. Complete error with Stack trace is in below screenshot.

image

**Review by ihor-sviziev — APPROVED** [review]
Approved ✔

Changes looks good.

**Comment by ihor-sviziev** [comment]
Note: I just checked - this sniff was added in https://github.com/magento/magento-coding-standard/pull/209 and wasn't covered with any tests. That's why the tests are not failing.

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by magento-engcom-team** [comment]
@sivaschenko the pull request successfully imported.

**Pull request merged**
