### PR TITLE
AC-679 Fix ruleset

### PR DESCRIPTION
**Pull request by jcuerdo**
system.xml is only placed in etc/adminhtml/system.xml https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-systemxml.html

### CODE REVIEW

**Review by svera — APPROVED** [review]

**Review by loginesta — APPROVED** [review]

**Comment by jcuerdo** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@jcuerdo an error occurred during the Pull Request import.

**Comment by jcuerdo** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@jcuerdo an error occurred during the Pull Request import.

**Comment by jcuerdo** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@jcuerdo an error occurred during the Pull Request import.

**Comment by svera** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@svera an error occurred during the Pull Request import.

**Comment by eliseacornejo** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@eliseacornejo an error occurred during the Pull Request import.

**Pull request merged**
