### PR TITLE
AC-1156: Move custom eslint tests to magento-coding-standard repo

### PR DESCRIPTION
**Pull request by loginesta**

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Comment by eliseacornejo** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@eliseacornejo an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Comment by loginesta** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by m2-github-services** [comment]
@loginesta an error occurred during the Pull Request import.

**Comment by loginesta** [comment]
closing this PR, since this other one has been merged https://github.com/magento-commerce/magento-coding-standard/pull/73

**Pull request closed without merging**
