### PR TITLE
Avoid infinite loop when Parse Error occurs

### PR DESCRIPTION
**Pull request by fredden**
One of our developers introduced a Parse Error into a template file. When `phpcs --standard=Magento2` ran as part of our automated testing process, it began using 100% CPU and never exited (until it was terminated automatically for taking too long). Investigation shows that the XSS Template sniff from this repository is at fault. I've managed to narrow down the cause and produced a testcase to reproduce this scenario. The proposed fix checks the return code of `PHP_CodeSniffer\Files\File::findNext()`, rather than blindly assuming this is an integer. I've not searched for other uses of this function within this codebase.

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Review by riconeitzel — APPROVED** [review]
looks good

**Comment by ihor-sviziev** [comment]
@sivaschenko, could you take a look? This change looks good to me

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento import pr to magento-commerce/magento-coding-standard

**Comment by magento-engcom-team** [comment]
@sivaschenko the pull request successfully imported.

**Pull request merged**
