### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KhushalGupta**
Fix broken link.

### CODE REVIEW

**Comment by lenaorobei** [comment]
@KhushalGupta please sing Adobe CLA.

**Comment by lenaorobei** [comment]
Closing due to inactivity.
@KhushalGupta please feel free to reopen and sign CLA. Thanks.

**Comment by DanielRuf** [comment]
I would rather rename the file. I'll open a new PR.

**Comment by DanielRuf** [comment]
There you go: https://github.com/magento/magento-coding-standard/pull/166

**Pull request closed without merging**
