### PR TITLE
Update supported PHP versions

### PR DESCRIPTION
**Pull request by fredden**
Magento currently supports PHP version 8.1.x and 8.2.x. This pull request updates the coding standard to match.
See also https://github.com/magento/magento2/commit/8559efcaa84281e833f58583898b7219a51f31d2 (where 7.4.x was removed) and https://github.com/magento/magento2/commit/80497d15f9f983a37debc6decbeef5dc34ce02d9 (where 8.2.x was added).

### CODE REVIEW

**Comment by fredden** [comment]
The tests which are failing here will be fixed by https://github.com/magento/magento-coding-standard/pull/455

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by sinhaparul** [comment]
@magento  import PR to magento-commerce/magento-coding-standard repository

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Comment by sinhaparul** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sinhaparul an error occurred during the Pull Request import.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sinhaparul** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sinhaparul an error occurred during the Pull Request import.

**Comment by sinhaparul** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sinhaparul an error occurred during the Pull Request import.

**Comment by hostep** [comment]
I'm not in favor of this PR, it would mean that more recent versions of the coding standards module (if they ever get tagged) can't be installed on older Magento shops (Magento 2.4.4 and 2.4.5 still support PHP 7.4 and are still receiving security updates for example).
As long as there is no code that's incompatible with PHP 7.4 in coding-standards module, we shouldn't drop support for it in my opinion.

**Comment by ihor-sviziev** [comment]
@hostep I think that's a good point!
But since PHP 7.4 reached the EOL half a year ago, we don't need to support it. Why? Because it's crucial to keep e-commerce projects with up-to-date software and receive security updates. And second - it will help to continue improving coding standards.
Those still on PHP 7.4 can continue using older versions of the standard. 

Refercenes: https://www.php.net/supported-versions.php
Please note that 2.4.4 and 2.4.5 are supported on PHP 8.1 
https://experienceleague.adobe.com/docs/commerce-operations/release/planning/lifecycle-policy.html?lang=en (

**Comment by hostep** [comment]
Yeah ok sure (be aware that Debian - and other vendors - keep patching unsupported PHP versions for years to come with security fixes even if official support is passed)

But anyway, it was just an opinion 🙂

**Comment by fredden** [comment]
The motivation for creating this pull request was that the automated tests were failing on older versions of PHP. The repository content has changed since then; looking at https://github.com/magento/magento-coding-standard/actions/runs/5203898335/jobs/9387379497, the automated tests seem to be passing now.

As an additional benefit, after this pull request has been merged, we can start using some of the language features introduced in PHP 8.1+ like `readonly` properties, and constructor property promotion.

**Comment by sinhaparul** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sinhaparul an error occurred during the Pull Request import.

**Comment by sinhaparul** [comment]
@magento  import pr to magento-commerce/magento-coding-standard repository

**Comment by sidolov** [comment]
"magento import pr to magento-commerce/magento-coding-standard repository

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@sidolov an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
https://github.com/magento import pr to magento-commerce/magento-coding-standard repository

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@mmansoor-magento an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@mmansoor-magento an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-commerce/magento-coding-standard repository

**Comment by m2-github-services** [comment]
@mmansoor-magento the Pull Request is successfully imported.

**Comment by ihor-sviziev** [comment]
@fredden @sinhaparul FYI there is test failures appeared on the main branch after merging changes from this PR.

**Comment by hostep** [comment]
Also (unless I'm mistaken), it appears that the stable version of the `phpcompatibility/php-compatibility` tool is used here. That stable version only supports up to PHP 7.4. If you need checks for PHP 8.1 or 8.2, you'll need the `dev-develop` version of it. That version contains a bunch of checks for PHP 8.0 and higher.

So I think that this change won't have any effect (or even a negative effect) since the stable version doesn't support PHP 8:
```diff
-    <config name="testVersion" value="7.4-"/>
+    <config name="testVersion" value="8.1-8.2"/>
```

**Pull request merged**
