### PR TITLE
No longer require a space before a colon for control structures using…

### PR DESCRIPTION
**Pull request by hostep**
… the alternative syntax

This fixes https://github.com/magento/magento-coding-standard/issues/118

Documentation: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#squizcontrolstructurescontrolsignature

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=132) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-coding-standard?pullRequest=132) before we can accept your contribution.<br/>

**Comment by hostep** [comment]
I've added a unit test, but for some reason it's not working properly. If somebody could give me a hint why not, that would be appreciated!

It might be because there is no corresponding Sniff added, but does that mean that no unit test is required in this case?

**Comment by hostep** [comment]
I've thought about it some more and it doesn't make much sense to have unit tests for this in the magento-coding-standard repo. The unit tests should be (and are already) part of the PHP_CodeSniffer repo.
So they are removed again over here.

**Comment by lenaorobei** [comment]
@hostep thank you for this improvement.

**Pull request merged**
